import type { Metadata } from "next";
import { Montserrat, Comfortaa } from 'next/font/google';
import "./globals.css";


export const metadata: Metadata = {
  title: "Vi-Tech",
  description: "Generated by create next app",
};


const montserrat = Montserrat({
  variable: '--font-sans',
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
});

const comfortaa = Comfortaa({
  variable: '--font-display',
  subsets: ['latin', 'cyrillic'],
  // Comfortaa обычно от 300 до 700 — выбери нужные:
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${comfortaa.variable} font-sans`}>

        {children}
      </body>
    </html>
  );
}
